### ISSUE TITLE
Better Error Reporting

### ISSUE THREAD

**Issue by jinankjain** [JonPulsifer/kubeaudit#3]
We need better error reporting in the case when there is no instance of kubernetes. Right now it just times out and dumps some error message like:

``` raw
panic: Get https://192.168.99.100:8443/apis/apps/v1beta1/deployments: dial tcp 192.168.99.100:8443: getsockopt: operation timed out

goroutine 1 [running]:
github.com/JonPulsifer/kubeaudit/cmd.getDeployments(0xc42057c140, 0x0)
	/Users/turingmachine/.go/src/github.com/JonPulsifer/kubeaudit/cmd/kubernetes.go:52 +0xda
github.com/JonPulsifer/kubeaudit/cmd.glob..func5(0x27f1da0, 0xc420191720, 0x0, 0x1)
	/Users/turingmachine/.go/src/github.com/JonPulsifer/kubeaudit/cmd/runAsNonRoot.go:55 +0xfd
github.com/JonPulsifer/kubeaudit/vendor/github.com/spf13/cobra.(*Command).execute(0x27f1da0, 0xc4201916e0, 0x1, 0x1, 0x27f1da0, 0xc4201916e0)
	/Users/turingmachine/.go/src/github.com/JonPulsifer/kubeaudit/vendor/github.com/spf13/cobra/command.go:651 +0x23a
github.com/JonPulsifer/kubeaudit/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x27f1b80, 0x0, 0xc4200002a8, 0xc420627f48)
	/Users/turingmachine/.go/src/github.com/JonPulsifer/kubeaudit/vendor/github.com/spf13/cobra/command.go:726 +0x339
github.com/JonPulsifer/kubeaudit/vendor/github.com/spf13/cobra.(*Command).Execute(0x27f1b80, 0x1, 0x1)
	/Users/turingmachine/.go/src/github.com/JonPulsifer/kubeaudit/vendor/github.com/spf13/cobra/command.go:685 +0x2b
github.com/JonPulsifer/kubeaudit/cmd.Execute()
	/Users/turingmachine/.go/src/github.com/JonPulsifer/kubeaudit/cmd/root.go:50 +0x31
main.main()
	/Users/turingmachine/src/github.com/Shopify/kubeaudit/main.go:26 +0x20
```

**Comment by jinankjain** [comment]
Idea to solve the problem:

- Using the current logging system and having two modes - debug and production mode
- In debug mode print the complete stack trace that could help in finding the bug
- In production/release mode just print the error message using the logger.

This seems the way to go forward I guess what do you say @JonPulsifer ?

**Comment by JonPulsifer** [comment]
@jinankjain sounds good to me! thanks 💯

**Comment by jinankjain** [comment]
PR is on its way :D
